### ISSUE TITLE
is there a way i can save rendered pdf using php code?

### ISSUE THREAD

**Issue by amitleuva1987** [alvarcarto/url-to-pdf-api#102]
I want to save the rendered pdf using php or html code like below. 

<a target="_blank" href="https://url-to-pdf-api.herokuapp.com/api/render?url=http://google.com&&emulateScreenMedia=false" class="btn btn-custom" download="download">Download pdf</a>

when i click on Download PDF, a pdf should get downloaded.

**Comment by kimmobrunfeldt** [comment]
This would require a modification to the code. I think a good implementation would be to add a `download=true` query parameter which would then cause the server to respond with correct download headers. 

I would accept a PR for this.

**Comment by kimmobrunfeldt** [comment]
Actually this is possible with attachmentName parameter already: https://github.com/alvarcarto/url-to-pdf-api/pull/46. It has gone in without documentation, I'll fix that.
