### ISSUE TITLE
Api stop working sometimes

### ISSUE THREAD

**Issue by miroslavsekulic** [alvarcarto/url-to-pdf-api#109]
Hello folks, first thank you for this library! 
But, sometimes, there is a problem with API, like now. For example if you try to open this link 
`https://url-to-pdf-api.herokuapp.com/api/render?url=http://google.com`
You will get this response 
![image](https://user-images.githubusercontent.com/45623984/59432771-63ee4700-8de8-11e9-9664-3556f7ed215d.png)
Any help with this?

**Comment by gdmartinez93** [comment]
I have the same message. Any idea about it?

**Comment by miroslavsekulic** [comment]
@gdmartinez93 
I think that their server was down. My solution is to use ` Puppeteer` library directly, to avoid third party api-s that you cannot control.

**Comment by kimmobrunfeldt** [comment]
Hi, the demo server is not meant for production usage. It runs in a free Heroku environment, and runs out of resources easily.
