### ISSUE TITLE
Help wanted. [Remove url from bottom of the pdf]

### ISSUE THREAD

**Issue by lupu60** [alvarcarto/url-to-pdf-api#112]
Hey, nice work btw with this project.

I have a question regarding of how puppeteer rendres the pdf.
By default, puppeteer adds the URL in the bottom of the pdf.
I see that in your pdf doesn't appear. How did you manage to remove that?
  
![image](https://user-images.githubusercontent.com/5337610/62411792-5cd20100-b601-11e9-9dcc-a2dd93723ef6.png)

**Comment by kimmobrunfeldt** [comment]
Thanks! Did you try `pdf.displayHeaderFooter` option? 

You can also check into https://github.com/puppeteer/puppeteer/issues. This project acts as a wrapper for Puppeteer, so in many cases, their issue tracker is actually more useful. 

Closing this as the option provided shoul help.
