### ISSUE TITLE
All text being rendered as bold

### ISSUE THREAD

**Issue by vanjoechua** [alvarcarto/url-to-pdf-api#129]
I installed this package in Heroku and its running nicely. However all my text is being rendered in "bold" while if I run the app in my local server (Windows 10) they are rendered correctly. Is there any parameter I can set to prevent this?

**Comment by massimoliani** [comment]
I'm just using it on a web app rendering html and is working fine.
I only fork the project from the original one and install on heroku, as
heroku want a git project to start.

*--------------------------*

dr. *Massimo Liani*

Goooled s.r.l.
Vial Lacchin 36/D
33077 - Sacile - PN

tel:3884484284


Il giorno gio 28 mag 2020 alle ore 01:40 vanjoechua <
notifications@github.com> ha scritto:

**Comment by vanjoechua** [comment]
I also tested it by printing just a random web page. all text was printed with heavy typeset. Somebody can help?

**Comment by vanjoechua** [comment]
I solved this by  loading the font using @font-face!

**Comment by germanger** [comment]
> I solved this by loading the font using @font-face!

Can you add more detail to your solution please?
