### ISSUE TITLE
setting this project up without Heroku

### ISSUE THREAD

**Issue by lmj0011** [alvarcarto/url-to-pdf-api#13]
I'm interested in running this project from an AWS EC2 instance.

I should have no problems doing that following these instructions correct?
https://github.com/alvarcarto/url-to-pdf-api#development

**Comment by adrianfalleiro** [comment]
You'll also need to make sure your EC2 instance has Chrome installed.

**Comment by lmj0011** [comment]
Headless Chrome or just the regular Chrome, also which version?

**Comment by adrianfalleiro** [comment]
I believe you need Chrome 59+

Puppeteer (the library that this project uses to interact with Chrome) will launch the browser in headless mode.

**Comment by lmj0011** [comment]
>I believe you need Chrome 59+

https://www.chromestatus.com/feature/5678767817097216

**Comment by kimmobrunfeldt** [comment]
Puppeteer should download a correct Chrome binary by default installed. You can find some details here: https://github.com/GoogleChrome/puppeteer/issues/807

**Comment by microbox** [comment]
I just publish a docker image for this project. You can setup this project using one single line of docker command:

```
docker run -d --name url2pdf microbox/node-url-to-pdf-api
```

for more details, please checkout https://github.com/microbox/node-url-to-pdf-api

**Comment by kimmobrunfeldt** [comment]
Docker image released by @microbox would be the way to go from my point of view. I updated this also into the readme. Thanks!
