### ISSUE TITLE
Are get links allowed ?

### ISSUE THREAD

**Issue by harismuntazir** [alvarcarto/url-to-pdf-api#157]
I Tried to get this url
https://url-to-pdf-api.herokuapp.com/api/render?url=https://egov.uok.edu.in/courseinfo/ugforms/prelogin/default2_wdsubnames.aspx?id=113994&courseyear=4

but it resulted in the following error..

{"status":400,"statusText":"Bad Request","errors":[{"field":["courseyear"],"location":"query","messages":["\"courseyear\" is not allowed"],"types":["object.allowUnknown"]}]}

What could be the problem

**Comment by cdwiegand** [comment]
Try url encoding the requested url (you have two ?s, the second should already be url encoded).

**Comment by Gunyon** [comment]
Like this:
https://url-to-pdf-api.herokuapp.com/api/render?url=https://egov.uok.edu.in/courseinfo/ugforms/prelogin/default2_wdsubnames.aspx**%3F**id=113994**%26**courseyear=4

**Comment by kimmobrunfeldt** [comment]
The demo has been limited to work with only certain URLs for security reasons.
