### ISSUE TITLE
Do not support Chinese Website

### ISSUE THREAD

**Issue by kuangthree** [alvarcarto/url-to-pdf-api#16]
Such as Baidu, a search engine like google in China. It cannot parse Chinese characters on this web page.
https://url-to-pdf-api.herokuapp.com/api/render?url=http://www.baidu.com

**Comment by riston** [comment]
This is something related to question here: https://github.com/alvarcarto/url-to-pdf-api/issues/5

**Comment by mjvcallibrity** [comment]
Just for clarification, this is what I see when I go to the link you provided, @kuangthree:

<img width="627" alt="screen shot 2017-10-09 at 6 42 18 am" src="https://user-images.githubusercontent.com/19933141/31334655-26c8d0c4-acbd-11e7-95ef-85bfc23b119e.png">

When I navigate to baidu.com myself, it looks the same as what is rendered by the link you provided. Is there something else you are expecting to see?

**Comment by kuangthree** [comment]
@mjvcallibrity 
Yes, that's what I want.   Now when I go to the link, I see what I expecting to see.  It seems that the problem has fixed. Thanks for your reminding!

**Comment by xjkwq1qq** [comment]
I have the same problem when build it in my system，when I test with baidu http://10.173.44.53:10002/api/render?url=http://www.baidu.com

like this
![Image of baidu_err](https://xjkwq1qq.github.io/imagesource/url-to-pdf/baidu_err.JPG)

is there something need setting?

**Comment by kuangthree** [comment]
@xjkwq1qq 
Maybe the response under this issue can help you. https://github.com/alvarcarto/url-to-pdf-api/issues/5

**Comment by xjkwq1qq** [comment]
@kuangthree 
i install on docker,not on Heroku

**Comment by mjvcallibrity** [comment]
@xjkwq1qq If I had to take a guess, whatever image you used in your docker install doesn't support chinese character text display. What OS image did you use in your docker installation? Do you know if that image supports chinese character text display?

**Comment by kimmobrunfeldt** [comment]
I fixed this in Heroku by adding this buildpack: https://github.com/debitoor/heroku-buildpack-converter-fonts. It installs a few more fonts to the Heroku environment. That would need to be done in the Docker setup separately.

**Comment by xjkwq1qq** [comment]
@mjvcallibrity @kimmobrunfeldt  thanks,I installation in ubuntu,it does not support hinese character text display default.I need to add a chinese font, it will be work

**Comment by kimmobrunfeldt** [comment]
The fix for font related issues are to install fonts into the system where this API is running. By default we're installing some fonts to Heroku.
