### ISSUE TITLE
options in .env not used

### ISSUE THREAD

**Issue by wtrdk** [alvarcarto/url-to-pdf-api#19]
When I alter the options in .env they are not used:
```
export NODE_ENV=development
export PORT=9990
export ALLOW_HTTP=true
```

When I use them as a prefix for the start command it works just fine:
```

ALLOW_HTTP=true PORT=9990 npm start
```

What am I doing wrong?

BTW, very nice piece of software!

**Comment by Cadiac** [comment]
Did you remember to set the environment variables by running `source .env` or `bash .env` after you changed the file?

**Comment by kimmobrunfeldt** [comment]
Thanks ! 🙇  Advice by @Cadiac should fix the issue. You need to load the .env file each time before starting the server. https://github.com/kennethreitz/autoenv or similar is a good tool to help managing it automatically.
