### ISSUE TITLE
Pass Header Parameters with the URL

### ISSUE THREAD

**Issue by sabya14** [alvarcarto/url-to-pdf-api#26]
How to send authentication parameter along with the url ?? 

trying something like this but failing
http://abc.abc.com:9000/api/render?url=http://abc.abc.com&setExtraHTTPHeaders={'header': 'value'}

**Comment by pendexgabo** [comment]
@sabya14 how are you planning on calling the service ? with curl?

**Comment by kimmobrunfeldt** [comment]
I haven't been personally using the different request parameters with this service, but the direction I'd want to see is to have full control to the request being made: https://github.com/alvarcarto/url-to-pdf-api/pull/99.

**Comment by kimmobrunfeldt** [comment]
Let's continue discussion here https://github.com/alvarcarto/url-to-pdf-api/pull/99
