### ISSUE TITLE
API key authentication

### ISSUE THREAD

**Issue by raquelxmoss** [alvarcarto/url-to-pdf-api#41]
Hi folks! Could someone please point me to some documentation on how to do API key authentication. There's mention of it in the README, but no instructions yet, and I didn't see anything relevant in the Puppeteer docs. Any help appreciated!

**Comment by kimmobrunfeldt** [comment]
Hi!

You can enable a simple token authentication by setting `API_TOKENS` environment variable to anything. It is meant to be a comma-separated list of acceptable tokens in plain text. So e.g. `API_TOKENS=token1,token2 npm start` should then require `x-api-key: token1` or `x-api-key: token2` header.

**Comment by raquelxmoss** [comment]
Thanks for the speedy response 😄 I'll give that a go
