### ISSUE TITLE
can i use the css style 'print' to set the page pdf style

### ISSUE THREAD

**Issue by lihaonanGY** [alvarcarto/url-to-pdf-api#44]
I want the content to appear on a separate page, not with other content

**Comment by darph** [comment]
you will need to pass `emulateScreenMedia: false` as a parameter to the request, to force chrome to parse print related CSS. With that chrome will afaik apply both `@media print { ... }` and `@page { ... }`.  

You can then control what content goes on which page using the [page-break-XXX](https://www.w3schools.com/cssref/pr_print_pageba.asp) rules.

**Comment by pavle-lekic-htec** [comment]
I tried that and it doesn't seem to work, or I'm not doing something right. I created a big table, and set `page-break-after: always;` rule to every 10th `<tr>` tag, hoping that it will break the page after it, but that doesn't happen. Am I doing something wrong?
