### ISSUE TITLE
Feature request: Support rendering images

### ISSUE THREAD

**Issue by esphen** [alvarcarto/url-to-pdf-api#49]
Hi,

First of all, thanks for this awesome project. It seems to be really well thought-out, so thank you for your efforts. I also really like the ability to render logged in pages by setting a cookie in the POST request.

Since you are using puppeteer, which also supports rendering pages to images via "screenshot", it would be possible to render images as well. Is this something you're interested in? We have some users which would like this, for example for dashboards that are displayed on a monitors.

**Comment by Echobob** [comment]
See https://github.com/alvarcarto/url-to-pdf-api/pull/43

**Comment by kimmobrunfeldt** [comment]
You can now use output=screenshot query parameter. See the screenshot parameters in https://github.com/alvarcarto/url-to-pdf-api#get-apirender.
