### ISSUE TITLE
All fonts are not rendered correctly in Heroku

### ISSUE THREAD

**Issue by kimmobrunfeldt** [alvarcarto/url-to-pdf-api#5]
E.g. Helvetica Neue is not rendered on Heroku. Url: https://url-to-pdf-api.herokuapp.com/api/render?url=https://github.com/kimmobrunfeldt/url-to-pdf-api/issues/5

My macbook:
<img width="843" alt="screenshot 2017-10-04 01 05 44" src="https://user-images.githubusercontent.com/1232405/31151459-36a24c3a-a8a0-11e7-9fa3-a3e227106ecf.png">

[macbook.pdf](https://github.com/kimmobrunfeldt/url-to-pdf-api/files/1354055/macbook.pdf)

Heroku:
<img width="846" alt="screenshot 2017-10-04 01 05 58" src="https://user-images.githubusercontent.com/1232405/31151460-3a8103dc-a8a0-11e7-9627-6cc374fae99a.png">

[heroku.pdf](https://github.com/kimmobrunfeldt/url-to-pdf-api/files/1354056/heroku.pdf)

**Comment by riston** [comment]
There will be always some difference between "your" pc and the rendering machine, depends on what you use Windows, Linux, OSX etc. The system font base will be always different, you can include some fonts with some custom font buildbacks, but be aware that the Heroku slug size is limited to ~300MB.

Some random example https://github.com/debitoor/heroku-buildpack-converter-fonts.

**Comment by kimmobrunfeldt** [comment]
I added the above mention buildpack, but paragraphs in github at least are bolded:
[heroku-fonts.pdf](https://github.com/alvarcarto/url-to-pdf-api/files/1367174/heroku-fonts.pdf)

**Comment by germanger** [comment]
How do you add a buildpack if the app was deployed to the dyno using Heroku Button?
