### ISSUE TITLE
Issue passing more than one parameter.

### ISSUE THREAD

**Issue by compwiz21** [alvarcarto/url-to-pdf-api#50]
If i try to pass more than one parameter, i get an error on the second parameter.
Example: https://urltopdf2.herokuapp.com/api/render?url=https://server1.outsystemscloud.com/automatedterritoryas/PDFEmail.aspx?Tenantid=109&Territoryid=564

If i browse to the url, works no problem. When i try to use url-to-pdf-api, i get the following error:
{"status":400,"statusText":"Bad Request","errors":[{"field":["Territoryid"],"location":"query","messages":["\"Territoryid\" is not allowed"],"types":["object.allowUnknown"]}]}

Again, if i leave off the last &Territoryid=564 it works, no error. Add it, error.

**Comment by pendexgabo** [comment]
@compwiz21 try doing a urlencode of the url before calling the server

https://msdn.microsoft.com/en-us/library/zttxte6w(v=vs.110).aspx   (.NET)
http://php.net/manual/en/function.urlencode.php (PHP)

**Comment by compwiz21** [comment]
I’ve already did the url encode. Still fails.

**Comment by kimmobrunfeldt** [comment]
Url encoding correctly works for me. This is working fine: https://url-to-pdf-api.herokuapp.com/api/render?url=https://server1.outsystemscloud.com/automatedterritoryas/PDFEmail.aspx%3FTenantid%3D109%26Territoryid%3D564
