### ISSUE TITLE
Run through Chrome Dom Distiller

### ISSUE THREAD

**Issue by billiob** [alvarcarto/url-to-pdf-api#54]
The Dom Distiller is a nice tool to remove clutter on web pages: https://github.com/chromium/dom-distiller
It would be great to be able to use it.

**Comment by kimmobrunfeldt** [comment]
This is a nice use case idea but I wouldn't want to introduce a Java dependency to solve this somewhat niche use case. If there are more interest towards to it, let's reopen.
