### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by rakanalh** [alvarcarto/url-to-pdf-api#6]
https://url-to-pdf-api.herokuapp.com/api/render?url=file:///etc/passwd

Actually shows the content of the file... as mentioned by erdbeerkaese, here:
https://news.ycombinator.com/item?id=15408217

**Comment by kimmobrunfeldt** [comment]
Thank you for opening the issue! Fixed in https://github.com/alvarcarto/url-to-pdf-api/commit/af5f96cc06fda90ea1dab5756e508aa11e139080
