### ISSUE TITLE
Cookies support

### ISSUE THREAD

**Issue by neslinesli93** [alvarcarto/url-to-pdf-api#62]
I was having difficulties getting the cookies to be sent with my request, and I think I may have found the problem. [This function here](https://github.com/alvarcarto/url-to-pdf-api/blob/master/src/http/pdf-http.js#L46) is missing `cookies` assignment, and therefore the resulting `cookies` array is always empty.

Am I missing something? Thanks for the library by the way - it's just awesome!

**Comment by lsaini** [comment]
I agree. Same case was with me as well and cookies were not set.

**Comment by kimmobrunfeldt** [comment]
Seems like a bug yes. I've missed this part in the PR review. Bug fix PR welcome.
