### ISSUE TITLE
Upgrade Puppeteer to latest

### ISSUE THREAD

**Issue by ram-you** [alvarcarto/url-to-pdf-api#65]
Hi, please upgrate puppeteer to latest (1.2.0).
Thank you.

**Comment by AustinTBiggs** [comment]
Yes please!

**Comment by AshleyPoole** [comment]
@kimmobrunfeldt would you be happy to accept PR https://github.com/alvarcarto/url-to-pdf-api/pull/74/ to upgrade Puppeteer? Apparently there's some important bug fixes that resolves issues with ws/socket issues.

**Comment by kimmobrunfeldt** [comment]
Puppeteer has now been upgraded to 1.6.0 in master. Also published in the demo app running in Heroku.
