### ISSUE TITLE
CSS filters causing image distortions

### ISSUE THREAD

**Issue by fractalawareness** [alvarcarto/url-to-pdf-api#67]
Just take a look at https://url-to-pdf-api.herokuapp.com/api/render?url=http://bennettfeely.com/filters&waitFor=1000

The first image (no css) has smooth lines but other images have glitches because of the filters applied to them. If you open the [source](http://bennettfeely.com/filters) in Chrome it has no such distortions.

**Comment by kimmobrunfeldt** [comment]
This issue belongs to https://github.com/GoogleChrome/puppeteer or even Google Chrome, which is the underlying piece doing the rendering.
