### ISSUE TITLE
Font weight ignored

### ISSUE THREAD

**Issue by pavle-lekic-htec** [alvarcarto/url-to-pdf-api#85]
I have an issue, whatever font-weight property I set it's being ignored. When I open html in Chrome it looks fine, but when I generate pdf from it everything has 'regular' font weight. Has anyone experienced this issue? Is there a workaround?

**Comment by egeersoz** [comment]
I have the same issue.

**Comment by kimmobrunfeldt** [comment]
I would redirect this issue to https://github.com/GoogleChrome/puppeteer. It belongs there more than it does here as that level of rendering issues are most probably happening lower level than what we can control here.
