### ISSUE TITLE
cookies

### ISSUE THREAD

**Issue by nk932714** [alvarcarto/url-to-pdf-api#88]
i am confused in assigning cooking in api. could anyone help me.  I have 3 cookies 
eg -  Evnetid = 6235765; sessionid = jshdak; documentID= sjdh; how to enter this in api.

i read the document and try to put the values but getting error every time could anyone help please?

**Comment by esvitaly** [comment]
@nk932714 try to use this branch https://github.com/esvitaly/url-to-pdf-api/tree/cookies-repair, until #83 will be accepted.

**Comment by kimmobrunfeldt** [comment]
Merged.
