### ISSUE TITLE
Question: Locked to Node 8.x.x

### ISSUE THREAD

**Issue by mblarsen** [alvarcarto/url-to-pdf-api#89]
Any reason why the package.json locks the node version to 8.x.x? Could we change it to ">=8.x.x"?

**Comment by kimmobrunfeldt** [comment]
To lock down the major node version. I think it's always wise to lock down the major, because stuff can automatically break according to semver (unless node has some additional guarantees). I'll bump the version to 10 which is the latest LTS now.
