### ISSUE TITLE
Support cookies

### ISSUE THREAD

**Issue by sbeckeriv** [alvarcarto/url-to-pdf-api#9]
I would not want to pass the hosted version auth cookies but locally I would like to pass in a url and a cookie to be set. This would allow me to generate, locally, pdfs of my authenticated pages. 

Thanks. It looks neat. 

Becker

**Comment by kimmobrunfeldt** [comment]
This would be a good feature definitely. I'll try to figure what could be a good way to solve this.

**Comment by kimmobrunfeldt** [comment]
I know it's not a direct solution to this but it would also be possible to implement url token based authentication, e.g.: `https://myapp.com/receipts/xyz?token=<longtoken>`. This is what I've personally planned to be able to render receipts.

**Comment by sbeckeriv** [comment]
Hello,

I did not see a related commit. Is there one coming or is not going to be implemented.

The token idea will not work for my needs.

Thank you again
Becker

**Comment by kimmobrunfeldt** [comment]
I believe this PR should solve your use case: https://github.com/alvarcarto/url-to-pdf-api/pull/21. It was merged to master.

Feel free to reopen this if you'd need something else. Thanks!
