### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [alvarcarto/url-to-pdf-api#92]
Hi, what is the current status of this project? Is it still maintained?

**Comment by kimmobrunfeldt** [comment]
Yes, this project is still maintained, but in a few hour blocks every 3 months or so. 

Help would be very welcome https://github.com/alvarcarto/url-to-pdf-api/issues/75 ! :)

**Comment by lucawen** [comment]
From what I'm seeing, not even merge requests are being accepted, so I think he died ...
