### ISSUE TITLE
render html issue

### ISSUE THREAD

**Issue by LukaszKiedrowski** [alvarcarto/url-to-pdf-api#94]
https://github.com/alvarcarto/url-to-pdf-api/blob/master/src/core/render-core.js#L92

If you will send html and try to change color of font-size using css then pdf is blank.

I see that the bug in comment has been fixed so page.setContent is working correctly so you could change line above to this one. 
```
await page.setContent(opts.html, opts.goto);
```

**Comment by kimmobrunfeldt** [comment]
Fixed now.
